- name: Install ntpsec
  ansible.builtin.apt:
    install_recommends: false
    name:
      # ntpd
      - ntpsec
      # hwclock
      - util-linux-extra
  notify:
    - Set HW clock
- name: Config for ntpdate
  ansible.builtin.template:
    src: templates/ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart ntpd
- name: Set timezone
  community.general.timezone:
    hwclock: "UTC"
    name: "{{ time.timezone }}"
  notify:
    - Restart crond
