- name: Basic server setup
  hosts: all
  # Override role defaults
  vars_files:
  - apt-packages.yml
  - users.yml
  - authorized-keys.yml
  tasks:
  # Update apt and install
  # necessary packages
  - name: Apt & packages
    include_role:
      name: apt
  # Ensure expected users exist
  - name: Users
    include_role:
      name: users
