- name: Reload iptables
  ansible.builtin.systemd_service:
    name: netfilter-persistent
    daemon_reload: true
    state: restarted
    enabled: true
- name: Reload docker
  ansible.builtin.systemd_service:
    name: docker
    daemon_reload: true
    state: restarted
    enabled: true
