- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    daemon_reload: true
    state: restarted
    enabled: true
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
    enabled: true
- name: Restart certbot
  ansible.builtin.systemd_service:
    name: certbot
    daemon_reload: true
    state: restarted
    enabled: true
- name: Reload certbot
  ansible.builtin.systemd:
    name: certbot
    state: reloaded
    enabled: true
- name: Restart php-fpm
  ansible.builtin.systemd_service:
    name: php8.3-fpm
    daemon_reload: true
    state: restarted
    enabled: true
