- name: Update apt repo(s)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  notify:
    - Upgrade all packages
- name: Install base packages
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    install_recommends: false
    name: "{{ apt.packages }}"
