- name: Install IMAP (dovecot)
  ansible.builtin.apt:
    install_recommends: false
    name:
      - dovecot-core
      - dovecot-imapd
      - dovecot-sieve
      - curl
  notify:
    - Restart dovecot
- name: Create sieve-pipe directory
  ansible.builtin.file:
    path: /etc/dovecot/sieve-pipe
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Copy rspam learn ham script
  ansible.builtin.template:
    src: rspamd-learn-ham.sh.j2
    dest: /usr/local/bin/rspamd-learn-ham.sh
    owner: root
    group: root
    mode: '0755'
  notify:
    - Compile sieve scripts (ham)
- name: Copy rspam learn spam script
  ansible.builtin.template:
    src: rspamd-learn-spam.sh.j2
    dest: /usr/local/bin/rspamd-learn-spam.sh
    owner: root
    group: root
    mode: '0755'
  notify:
    - Compile sieve scripts (spam)
- name: Configure dovecot
  ansible.builtin.template:
    src: templates/dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload dovecot
