mail:  # noqa: var-naming[no-role-prefix] - see doc/STATUS.adoc
  aliases:
    - alias: postmaster
      forwards:
        - root
    - alias: www-data
      forwards:
        - root
  ssl:
    cert: /etc/letsencrypt/live/{{ hostname_fqdn }}/fullchain.pem
    key: /etc/letsencrypt/live/{{ hostname_fqdn }}/privkey.pem
