mail:
  aliases:
    - alias: postmaster
      forwards:
        - root
    - name: www-data
      forwards:
        - root
  ssl:
    cert: /etc/letsencrypt/live/{{ hostname_fqdn }}/fullchain.pem
    key: /etc/letsencrypt/live/{{ hostname_fqdn }}/privkey.pem
    ca: /etc/letsencrypt/live/{{ hostname_fqdn }}/chain.pem
