apt:
  packages:
    - aptitude
    - bash
    - bash-completion
    - btop
    - ca-certificates
    - curl
    - git
    - htop
    - less
    - luarocks
    - iputils-ping
    - logrotate
    - python-is-python3
    - python3
    - screen
    - ssh
    - sudo
    - tmux
    - unattended-upgrades
    - neovim
    - wget
    - xxd
