- name: Install dependencies
  ansible.builtin.apt:
    install_recommends: false
    name:
      - hostname
      - locales
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname_fqdn }}"
- name: Copy locale.gen file
  ansible.builtin.template:
    src: templates/locale.gen.j2
    dest: /etc/locale.gen
    owner: root
    group: root
    mode: "0644"
  register: result
  notify:
    - Generate locales
    - Set default locales
    - Set LANG
