= Environment Setup
include::.attributes-page.adoc[]

:url-docker: https://www.docker.com[Docker^]
:url-wsl: https://learn.microsoft.com/en-us/windows/wsl[Windows Subsystem for Linux^]
:url-vscode: https://code.visualstudio.com[Visual Studio Code^]

The development container consists of two link:{url-docker} containers and a compose file to create a network between both containers.
All configuration for the environment is kept in the directory `.devcontainer`.

== Host Setup

The Linux host should have the following packages installed (Ubuntu-based distro as example):

[source, bash]
----
sudo apt update
sudo apt install \
  --no-install-recommends \
    containerd \
    docker-buildx \
    docker.io
----

And - of course - the installation of link:{url-vscode}.

Intallation on link:{url-wsl} running *Ubuntu 24.04* works fine.

=== Docker Mounts

The controller node maps configuration files from the host to provide the same environment as on the host.

[cols="h,m,d", options="autowidth"]
|===
| Bash config | `~/.bashrc` | Prompts, functions, etc.
| git config | `~/.gitconfig` | Aliases, etc.
| General config dir | `~/.config/` | Additional configuration settings
|===

The file `.devcontainer/devcontainer.json` may be adapted easily to accomodate other config files (e.g. `zsh` settings).
