- name: Restart rspamd
  ansible.builtin.systemd:
    name: rspamd
    state: restarted
    enabled: true
- name: Reload rspamd
  ansible.builtin.systemd:
    name: rspamd
    state: reloaded
    enabled: true
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
    enabled: true
