- name: Download Nextcloud
  ansible.builtin.get_url:
    url: "https://download.nextcloud.com/server/releases/latest.tar.bz2"
    dest: /tmp/nextcloud.tar.bz2
    owner: root
    group: root
    mode: "0644"
- name: Extract Nextcloud
  ansible.builtin.unarchive:
    src: /tmp/nextcloud.tar.bz2
    dest: /var/www/nextcloud
    remote_src: true
    extra_opts: [--strip-components=1]
- name: Set ownership for Nextcloud files
  ansible.builtin.file:
    path: /var/www/nextcloud
    owner: www-data
    group: www-data
    recurse: true
- name: Add cron job for Nextcloud
  ansible.builtin.cron:
    name: "Nextcloud background job"
    minute: "*/5"
    user: www-data
    job: "/usr/bin/php -f /var/www/nextcloud/cron.php"
