version: "3.7"

name: ansible

services:
  ansible-managed:
    image: ansible-managed
    build:
      context: .
      dockerfile: Dockerfile.managed
      tags:
      - ansible-managed:latest
      # Build time information, e.g.
      # user name, password, etc.
      secrets:
      - username
      - password
    init: true
    hostname: managed
    expose:
    - 22
    networks:
      ansible-network:
        ipv4_address: &ref_managed_ipv4 172.16.200.3

  ansible-controller:
    image: ansible-controller
    build:
      context: .
      dockerfile: Dockerfile.controller
      tags:
      - ansible-controller:latest
      # Build time information, e.g.
      # user name, password, etc.
      secrets:
      - username
      - password
      - docker-gid
    init: true
    # Add /etc/hosts entry for
    # managed node for easier access
    # without DNS
    extra_hosts:
      managed: *ref_managed_ipv4
    hostname: controller
    networks:
      ansible-network:
        ipv4_address: 172.16.200.2

networks:
  ansible-network:
    name: ansible-network
    ipam:
      driver: default
      config:
      - subnet: 172.16.200.0/24
        ip_range: 172.16.200.0/24

secrets:
  username:
    file: .username
  password:
    file: .password
  docker-gid:
    file: .docker-gid
