- name: Restart dovecot
  ansible.builtin.systemd:
    name: dovecot
    daemon-reload: true
    state: restarted
    enabled: true
- name: Reload dovecot
  ansible.builtin.systemd:
    name: dovecot
    state: reloaded
    enabled: true
- name: Compile sieve scripts (ham)
  ansible.builtin.command:
    cmd: sievec /etc/dovecot/sieve/learn-ham.sieve
  args:
    removes: /nonexistent-file-to-force-run
  notify:
    - Reload dovecot
- name: Compile sieve scripts (spam)
  ansible.builtin.command:
    cmd: sievec /etc/dovecot/sieve/learn-spam.sieve
  args:
    removes: /nonexistent-file-to-force-run
  notify:
    - Reload dovecot
