- name: Add users
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    create_home: "{{ item.create_home }}"
    password: "{{ item.password }}"
    append: true
  loop: "{{ users.users }}"
  loop_control:
    label: "{{ item.name }}"
- name: Add authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.public_key }}"
  loop: "{{ users.authorized_keys }}"
  loop_control:
    label: "{{ item.name }}"
