- name: Install user management packages
  ansible.builtin.apt:
    install_recommends: false
    name:
      - sudo
      - passwd
- name: Add groups
  ansible.builtin.group:
    name: "{{ item.group }}"
  loop: "{{ users.users }}"
  loop_control:
    label: "{{ item.group }}"
- name: Group sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/sudo_nopasswd
    create: true
    owner: root
    group: root
    mode: '0440'
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: Add users
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups }}"
    create_home: "{{ item.create_home }}"
    password: "{{ item.password }}"
    append: true
  loop: "{{ users.users }}"
  loop_control:
    label: "{{ item.name }}"
- name: Add authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.public_key }}"
  loop: "{{ users.authorized_keys }}"
  loop_control:
    label: "{{ item.name }}"
