- name: Install postfix
  ansible.builtin.apt:
    install_recommends: false
    name:
      - postfix
    update_cache: true
  notify:
    - Restart postfix
- name: Configure postfix (main.cf)
  ansible.builtin.template:
    src: templates/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload postfix
- name: Configure postfix (master.cf)
  ansible.builtin.copy:
    src: files/postfix/master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload postfix
- name: Configure mail aliases
  ansible.builtin.template:
    src: templates/postfix/aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: "0644"
  notify:
    - Compile mail aliases
- name: Configure virtual mail aliases
  ansible.builtin.template:
    src: templates/postfix/valiases.j2
    dest: /etc/valiases
    owner: root
    group: root
    mode: "0644"
  notify:
    - Compile virtual mail aliases
