- name: Install fail2ban
  ansible.builtin.package:
    install_recommends: false
    name:
      - fail2ban
  notify:
    - Restart fail2ban
- name: Configure fail2ban
  ansible.builtin.copy:
    src: files/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload fail2ban
