- name: Generate locales
  ansible.builtin.command:
    cmd: "locale-gen"
  changed_when: true
- name: Set default locales
  ansible.builtin.debconf:
    name: locales
    question: locales/default_environment_locale
    value: "{{ locales.locale }}"
    vtype: select
- name: Set LANG
  ansible.builtin.command:
    cmd: "localectl set-locale LANG={{ locales.locale }} LC_TIME={{ locales.locale_alt }}"
  changed_when: true
