- name: Install docker
  ansible.builtin.apt:
    install_recommends: false
    name:
      - docker.io
      - docker-buildx
      - docker-compose-v2
      - pigz
- name: Systemd enable docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true
- name: Systemd enable containerd
  ansible.builtin.systemd_service:
    name: containerd
    state: started
    enabled: true
- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: docker
    append: true
  loop: "{{ docker.users }}"
