- name: Restart postfix
  ansible.builtin.systemd:
    name: postfix
    state: restarted
    enabled: true
- name: Reload postfix
  ansible.builtin.systemd:
    name: postfix
    state: reloaded
    enabled: true
- name: Compile mail aliases
  ansible.builtin.command: newaliases
  args:
    creates: /always_run_newaliases
  notify:
    - Reload postfix
- name: Compile virtual mail aliases
  ansible.builtin.command: postmap /etc/valiases
  args:
    creates: /etc/valiases.db
  notify:
    - Reload postfix
- name: Restart rspamd
  ansible.builtin.systemd:
    name: rspamd
    state: restarted
    enabled: true
- name: Reload rspamd
  ansible.builtin.systemd:
    name: rspamd
    state: reloaded
    enabled: true
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
    enabled: true
