- name: Install sshd
  ansible.builtin.apt:
    install_recommends: false
    name:
      - openssh-server
- name: Check remote sshd key ed25519
  ansible.builtin.stat:
    path: "/etc/ssh/ssh_{{ hostname }}_ed25519_key"
    get_checksum: true
    checksum_algorithm: "sha256"
  register: ed25519_checksum
- name: Copy sshd ed25519 key
  ansible.builtin.copy:
    src: "files/ssh_{{ hostname }}_ed25519_key.aes256"
    dest: "/etc/ssh/ssh_{{ hostname }}_ed25519_key"
    decrypt: true
    owner: root
    group: root
    mode: "0600"
  loop: "{{ sshd.host_keys }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name == "ed25519"
    - ed25519_checksum != item.sha256
  notify: Restart sshd
- name: Check remote sshd key rsa
  ansible.builtin.stat:
    path: "/etc/ssh/ssh_{{ hostname }}_rsa_key"
    get_checksum: true
    checksum_algorithm: "sha256"
  register: rsa_checksum
- name: Copy sshd rsa key
  ansible.builtin.copy:
    src: "files/ssh_{{ hostname }}_rsa_key.aes256"
    dest: "/etc/ssh/ssh_{{ hostname }}_rsa_key"
    decrypt: true
    owner: root
    group: root
    mode: "0600"
  loop: "{{ sshd.host_keys }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name == "rsa"
    - rsa_checksum != item.sha256
  notify: Restart sshd
- name: Copy sshd moduli
  ansible.builtin.copy:
    src: files/moduli
    dest: /etc/ssh/moduli
    owner: root
    group: root
    mode: "0644"
  notify: Restart sshd
- name: SSHd config
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  notify: Restart sshd
- name: Remove small DH moduli
  ansible.builtin.copy:
    src: files/moduli
    dest: /etc/ssh/moduli
    owner: root
    group: root
    mode: "0644"
  notify: Restart sshd
- name: Systemd enable sshd
  ansible.builtin.systemd_service:
    name: ssh
    state: started
    enabled: true
